"""Initial migrate

Revision ID: 7f8eb4b31e95
Revises: 
Create Date: 2020-07-20 20:26:20.124785

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7f8eb4b31e95'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('guest',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('phone_number', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_guest_name'), 'guest', ['name'], unique=False)
    op.create_index(op.f('ix_guest_phone_number'), 'guest', ['phone_number'], unique=True)
    op.create_table('table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('floor', sa.Integer(), nullable=True),
    sa.Column('room', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_table_floor'), 'table', ['floor'], unique=False)
    op.create_index(op.f('ix_table_room'), 'table', ['room'], unique=False)
    op.create_table('reservation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('guest_id', sa.Integer(), nullable=True),
    sa.Column('table_id', sa.Integer(), nullable=True),
    sa.Column('reservation_time_from', sa.DateTime(), nullable=True),
    sa.Column('reservation_time_to', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['guest_id'], ['guest.id'], ),
    sa.ForeignKeyConstraint(['table_id'], ['table.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reservation_reservation_time_from'), 'reservation', ['reservation_time_from'], unique=False)
    op.create_index(op.f('ix_reservation_reservation_time_to'), 'reservation', ['reservation_time_to'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reservation_reservation_time_to'), table_name='reservation')
    op.drop_index(op.f('ix_reservation_reservation_time_from'), table_name='reservation')
    op.drop_table('reservation')
    op.drop_index(op.f('ix_table_room'), table_name='table')
    op.drop_index(op.f('ix_table_floor'), table_name='table')
    op.drop_table('table')
    op.drop_index(op.f('ix_guest_phone_number'), table_name='guest')
    op.drop_index(op.f('ix_guest_name'), table_name='guest')
    op.drop_table('guest')
    # ### end Alembic commands ###
